version: '3.8'

services:
  frontend:
    image: 5c1518c4d241
    ports:
      - "5000:5000"
    environment:
    - FRONT_END_IMAGE_UPLOAD=http://frontend:5000/upload-image
    - SPEAK_SERVICE=http://frontend:5000/rosie-speak
    - THINK_SERVICE=http://think_service:5080/think
    - THINK_SERVICE_UPLOAD_CONTEXT=http://think_service:5080/upload-context
    - OPENAI_API_KEY=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

  think_service:
    image: 36d04c3e8244
    env_file: .env
    ports:
      - "5080:5080"
    devices:
      - /dev:/dev
    environment:
      - FRONT_END_IMAGE_UPLOAD=http://frontend:5000/upload-image
      - SPEAK_SERVICE=http://frontend:5000/rosie-speak
      - THINK_SERVICE=http://think_service:5080/think
      - THINK_SERVICE_UPLOAD_CONTEXT=http://think_service:5080/upload-context
      - OPENAI_API_KEY=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
    command: 
      - /bin/sh
      - -c
      - |
        #!/bin/sh
        sleep 50
        exec python3 /app/thinking.py
    depends_on:
      - frontend